version: '3.8'

services:
  friends:
    build: ./
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1998132"
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - postgres

volumes:
  pgadmin-data:

networks:
  postgres:
    driver: bridge