version: '3.8'

services:
  friends:
    depends_on:
      - postgres
    build: ./
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      CONNECTION_DRIVER_CLASS: org.postgresql.Driver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1998132"
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"

networks:
  postgres:
    driver: bridge